OPENALTERNATIVE_DATA = {
    "popular_software_list": [
        {"name": "Spotify Alternatives", "count": 2},
        {"name": "Notion Alternatives", "count": 19},
        {"name": "Claude Code Alternatives", "count": 15},
        {"name": "Lovable Alternatives", "count": 6},
        {"name": "n8n Alternatives", "count": 6},
        {"name": "Wispr Flow Alternatives", "count": 6},
        {"name": "Cursor Alternatives", "count": 15},
        {"name": "CapCut Alternatives", "count": 4},
        {"name": "Power BI Alternatives", "count": 10},
        {"name": "Discord Alternatives", "count": 9},
        {"name": "Pocket Alternatives", "count": 9},
        {"name": "Microsoft Teams Alternatives", "count": 15},
    ],
    "popular_categories_list": [
        {"name": "Low-Code/No-Code Platforms", "count": 37},
        {"name": "AI Agent Platforms", "count": 21},
        {"name": "Project Management Suites", "count": 21},
        {"name": "AI Personal Assistants", "count": 20},
        {"name": "PaaS & Deployment Tools", "count": 19},
        {"name": "Workflow Automation Tools", "count": 16},
        {"name": "Web Analytics", "count": 17},
        {"name": "AI Chat Interfaces", "count": 16},
        {"name": "Note-Taking Tools", "count": 15},
        {"name": "Infrastructure Monitoring Tools", "count": 16},
        {"name": "Customer Communication Platforms", "count": 15},
        {"name": "Backend-as-a-Service (BaaS) Tools", "count": 16},
    ],
    "footer_links": {
        "browse": [
            {"name": "Tools", "href": "/browse"},
            {"name": "Alternatives", "href": "/alternatives"},
            {"name": "Categories", "href": "/categories"},
            {"name": "Self-hosted", "href": "/self-hosted"},
            {"name": "Tech Stacks", "href": "/tech-stacks"},
            {"name": "Tags", "href": "/tags"},
            {"name": "Licenses", "href": "/licenses"},
            {"name": "Discount Codes", "href": "/discount-codes"},
        ],
        "quick_links": [
            {"name": "Contact us", "href": "/contact"},
            {"name": "Submit", "href": "/submit"},
            {"name": "Blog", "href": "/blog"},
            {"name": "About Us", "href": "/about"},
            {"name": "Advertise", "href": "/advertise"},
        ],
        "other_products": [
            {"name": "Shadcnblocks.com", "href": "https://shadcnblocks.com"},
            {"name": "Dirstarter", "href": "https://dirstarter.com"},
            {"name": "TerminalDock", "href": "https://terminaldock.com"},
            {"name": "EuroAlternative", "href": "https://neroalternative.com"},
            {"name": "DevSuite", "href": "https://devsuite.ai"},
            {"name": "OpenAds", "href": "https://openads.com"},
        ]
    },
    "categories": [
        {"name": "AI & Machine Learning", "slug": "ai-ml", "count": 37, "icon": "🤖", "description": "AI/ML platforms, tools and frameworks", "subcategories": ["AI Development Platforms", "Machine Learning Infrastructure", "AI Security & Privacy", "AI Interaction & Interfaces"]},
        {"name": "Business Software", "slug": "business", "count": 42, "icon": "💼", "description": "CRM, ERP, finance, HR and operations", "subcategories": ["CRM & Sales", "ERP & Operations", "Finance & Accounting", "Human Resources", "Marketing & Customer Engagement", "Customer Support & Success", "E-commerce Platforms", "Project & Work Management", "Collaboration & Communication", "Scheduling & Event Management", "Document Management & E-Signatures", "Forms & Surveys", "Compliance & Risk Management", "Legal"]},
        {"name": "Community & Social", "slug": "community", "count": 18, "icon": "👥", "description": "Social networking and community platforms", "subcategories": ["Social Networking", "Community Building Platforms", "Collaboration & Feedback"]},
        {"name": "Content & Publishing", "slug": "content", "count": 28, "icon": "📝", "description": "CMS, publishing and content platforms", "subcategories": ["Content Management Systems", "Community Platforms", "Documentation & Knowledge Base", "Learning Management Systems", "Digital Asset Management", "Publishing", "Blogging & Personal Sites"]},
        {"name": "Data & Analytics", "slug": "data-analytics", "count": 24, "icon": "📊", "description": "Analytics, BI and data platforms", "subcategories": ["Web & Product Analytics", "Business Intelligence & Reporting", "Data Engineering & Integration", "Data Warehousing & Processing", "Data Extraction & Web Scraping"]},
        {"name": "Developer Tools", "slug": "devtools", "count": 55, "icon": "🛠️", "description": "Software development tooling and platforms", "subcategories": ["Website Builders", "IDEs & Code Editors", "Frameworks & Platforms", "API Development & Testing", "Testing & Quality Assurance", "Version Control & Collaboration", "Code Analysis & Transformation", "Build & Deployment", "Integration Platforms", "AI Assisted Coding", "Terminals"]},
        {"name": "Infrastructure & Operations", "slug": "infra", "count": 48, "icon": "☁️", "description": "Cloud, infrastructure and operations tools", "subcategories": ["Search Engines", "Cloud Infrastructure Management", "Server & VM Management", "Monitoring & Observability", "Databases", "Networking & Connectivity", "Orchestration & Scheduling", "Messaging & Event Streaming", "Storage Solutions", "Backup & Recovery"]},
        {"name": "Miscellaneous", "slug": "misc", "count": 22, "icon": "📦", "description": "Finance, design, media and more", "subcategories": ["Finance & Fintech", "Design & Prototyping", "Cryptocurrency & Blockchain", "Gaming", "Internet of Things", "Logistics & Supply Chain", "Media & Streaming", "Photo & Video Editors"]},
        {"name": "Productivity & Utilities", "slug": "productivity", "count": 35, "icon": "⚡", "description": "Productivity tools and utilities", "subcategories": ["Note Taking & Knowledge Management", "Password & Secret Management", "Screen Capture & Recording", "File Management & Sync", "Email & Communication", "Automation", "Time & Task Management", "Personal Finance Management", "Design & Visualization", "Bookmark & Content Management", "Remote Desktop & Access", "Browsers & Extensions", "Input & Dictation"]},
        {"name": "Security & Privacy", "slug": "security", "count": 26, "icon": "🔒", "description": "Security and privacy tools", "subcategories": ["Identity & Access Management", "Secrets Management", "Threat Detection & Response", "Network Security", "Data Security & Privacy", "Application Security", "Fraud Prevention"]},
    ],
    "popular_alternatives": [
        {"proprietary": "Spotify", "open_source": "Navidoom", "url": "https://navidrome.org", "stars": 12, "category": "Media", "description": "Access millions of songs, podcasts, and playlists instantly with personalized recommendations and offline listening across all your devices.", "count": 2},
        {"proprietary": "Notion", "open_source": "AppFlowy", "url": "https://appflowy.io", "stars": 58, "category": "Note-Taking & Docs", "description": "An all-in-one workspace for note-taking, project management, knowledge sharing, and collaboration across teams.", "count": 19},
        {"proprietary": "Claude Code", "open_source": "Aider", "url": "https://aider.chat", "stars": 25, "category": "Developer Tools", "description": "Advanced AI coding assistant that helps developers write, debug, and optimize code across multiple programming languages with intelligent suggestions and explanations.", "count": 15},
        {"proprietary": "Lovable", "open_source": "OpenCode", "url": "https://opencode.ai", "stars": 5, "category": "Developer Tools", "description": "Create fully functional applications by describing your idea, with AI-powered code generation and beautiful design.", "count": 6},
        {"proprietary": "Claude", "open_source": "Open WebUI", "url": "https://openwebui.com", "stars": 138, "category": "AI Chat Interfaces", "description": "A next generation AI assistant built for work and trained to be safe, accurate, and secure.", "count": 14},
        {"proprietary": "n8n", "open_source": "n8n", "url": "https://n8n.io", "stars": 52, "category": "Workflow Automation", "description": "AI workflow automation platform that connects apps and services without coding. Build complex integrations with drag-and-drop interface.", "count": 6},
        {"proprietary": "YouTube", "open_source": "Invidious", "url": "https://invidio.us", "stars": 4, "category": "Media", "description": "Watch, upload and share videos globally on the world's largest video platform with billions of hours of content.", "count": 5},
        {"proprietary": "Netflix", "open_source": "Jellyfin", "url": "https://jellyfin.org", "stars": 52, "category": "Media", "description": "Watch thousands of movies, TV shows, and documentaries on-demand with personalized recommendations and offline viewing.", "count": 1},
        {"proprietary": "Wispr Flow", "open_source": "OpenClaw", "url": "https://openclaw.ai", "stars": 374, "category": "AI Personal Assistants", "description": "Flow transforms complex workflows into intelligent automation using AI-powered visual builders that connect your apps and data seamlessly.", "count": 6},
        {"proprietary": "Obsidian", "open_source": "Logseq", "url": "https://logseq.com", "stars": 35, "category": "Note-Taking & Docs", "description": "A powerful markdown-based knowledge base that works on local files, helping you build a personal knowledge graph for better learning and idea management.", "count": 16},
        {"proprietary": "Canva", "open_source": "Penpot", "url": "https://penpot.app", "stars": 35, "category": "Design & Creative", "description": "An online design and publishing tool that makes graphic design simple for creating social media graphics, presentations, posters, and more.", "count": 2},
        {"proprietary": "Grok", "open_source": "Ollama", "url": "https://ollama.ai", "stars": 130, "category": "AI Chat Interfaces", "description": "A free AI assistant designed by xAI to maximize truth and objectivity. Offers real-time search, image generation, trend analysis, and more.", "count": 10},
        {"proprietary": "Cursor", "open_source": "VSCodium", "url": "https://vscodium.com", "stars": 26, "category": "Developer Tools", "description": "AI-powered code editor that enhances programming productivity with intelligent autocomplete, code generation, and real-time assistance.", "count": 15},
        {"proprietary": "CapCut", "open_source": "Shotcut", "url": "https://shotcut.org", "stars": 10, "category": "Design & Creative", "description": "Free video editing app that lets you create professional-quality videos with advanced editing tools, effects, and templates.", "count": 4},
        {"proprietary": "Power BI", "open_source": "Metabase", "url": "https://metabase.com", "stars": 40, "category": "Analytics", "description": "A business analytics service by Microsoft that allows you to visualize and analyze your data with powerful interactive dashboards and reports.", "count": 10},
        {"proprietary": "Discord", "open_source": "Revolt", "url": "https://revolt.chat", "stars": 28, "category": "Communication", "description": "A free voice, video, and text chat app for gamers and non-gamers alike. Chat, hang out, and stay close with your friends and communities.", "count": 9},
        {"proprietary": "Perplexity", "open_source": "Open WebUI", "url": "https://openwebui.com", "stars": 138, "category": "AI Chat Interfaces", "description": "An AI-powered answer engine that provides accurate, trusted, and real-time answers to any question.", "count": 12},
        {"proprietary": "Pocket", "open_source": "LinkAce", "url": "https://linkace.org", "stars": 3, "category": "Productivity", "description": "A digital bookmarking tool that allows you to save articles, videos, and other content to read later, even offline.", "count": 9},
        {"proprietary": "NotebookLM", "open_source": "AnythingLLM", "url": "https://anythingllm.com", "stars": 60, "category": "AI Chat Interfaces", "description": "AI-powered research assistant that transforms your documents into interactive conversations, summaries, and insights.", "count": 3},
        {"proprietary": "Microsoft Teams", "open_source": "Mattermost", "url": "https://mattermost.com", "stars": 30, "category": "Communication", "description": "Cloud-based collaboration app for messaging, video calls, meetings, and file sharing. Integrates with Office 365.", "count": 15},
        {"proprietary": "ChatGPT", "open_source": "Open WebUI", "url": "https://openwebui.com", "stars": 138, "category": "AI Chat Interfaces", "description": "An AI chatbot, capable of understanding and generating human-like text, assisting in conversations, answering queries, and more.", "count": 14},
        {"proprietary": "OneNote", "open_source": "Joplin", "url": "https://joplinapp.org", "stars": 55, "category": "Note-Taking & Docs", "description": "Organize notes, ideas, and info across devices. Collaborate, sync, and search easily. Ideal for work, study, and personal use.", "count": 12},
        {"proprietary": "Photoshop", "open_source": "GIMP", "url": "https://gimp.org", "stars": 18, "category": "Design & Creative", "description": "A raster graphics editor developed by Adobe that allows users to create and edit images and graphics.", "count": 3},
        {"proprietary": "Google Drive", "open_source": "Nextcloud", "url": "https://nextcloud.com", "stars": 28, "category": "Hosting & Infrastructure", "description": "A cloud storage and file management service that allows users to store files in the cloud and synchronize across devices.", "count": 12},
        {"proprietary": "Miro", "open_source": "Affine", "url": "https://affine.pro", "stars": 69, "category": "Collaborative Workspaces", "description": "The innovation workspace where teams manage projects, design products, and build the future together.", "count": 7},
        {"proprietary": "Loom", "open_source": "Cap", "url": "https://cap.so", "stars": 19, "category": "Screen Recording", "description": "A video messaging tool that helps you get your message across through instantly shareable videos.", "count": 7},
        {"proprietary": "Microsoft 365", "open_source": "OnlyOffice", "url": "https://onlyoffice.com", "stars": 5, "category": "Productivity", "description": "A cloud-based suite of business applications including Office, SharePoint, Exchange, and Teams.", "count": 6},
        {"proprietary": "Linear", "open_source": "Plane", "url": "https://plane.so", "stars": 50, "category": "Project Management", "description": "Streamlines issues, projects, and roadmaps. Purpose-built for modern product development.", "count": 13},
        {"proprietary": "Airtable", "open_source": "NocoDB", "url": "https://nocodb.com", "stars": 63, "category": "Databases", "description": "A cloud-based platform that combines the simplicity of a spreadsheet with the complexity of a database.", "count": 9},
        {"proprietary": "Screen Studio", "open_source": "OBS Studio", "url": "https://obsproject.com", "stars": 62, "category": "Screen Recording", "description": "Screen recorder for macOS. Create engaging product demos, courses, tutorials, and social media videos.", "count": 7},
        {"proprietary": "Skype", "open_source": "Jitsi Meet", "url": "https://jitsi.org", "stars": 25, "category": "Video & Conferencing", "description": "Free video chat, messaging & affordable international calls. Create instant online video calls with one click.", "count": 5},
        {"proprietary": "Supabase", "open_source": "Appwrite", "url": "https://appwrite.io", "stars": 56, "category": "Backend-as-a-Service", "description": "An open-source Firebase alternative, providing database, authentication, real-time subscriptions, and storage.", "count": 20},
        {"proprietary": "Gmail", "open_source": "ProtonMail", "url": "https://proton.me", "stars": 5, "category": "Communication", "description": "A free email service developed by Google, offering secure webmail, POP3, IMAP access, and spam filtration.", "count": 4},
        {"proprietary": "Firefox", "open_source": "Chromium", "url": "https://chromium.org", "stars": 20, "category": "Browsers", "description": "The browser that puts your privacy first — and always has.", "count": 6},
        {"proprietary": "Jira", "open_source": "Plane", "url": "https://plane.so", "stars": 50, "category": "Project Management", "description": "Plan, track, and release world-class software with the number one project management tool for agile teams.", "count": 20},
        {"proprietary": "Figma", "open_source": "Penpot", "url": "https://penpot.app", "stars": 35, "category": "Design & Creative", "description": "A collaborative interface design tool that enables the entire team's design process to happen in one online tool.", "count": 5},
        {"proprietary": "Adobe Premiere Pro", "open_source": "Shotcut", "url": "https://shotcut.org", "stars": 10, "category": "Design & Creative", "description": "Professional video editing software for polished films with color correction, audio mixing, and more.", "count": 4},
        {"proprietary": "Confluence", "open_source": "Outline", "url": "https://outline.com", "stars": 29, "category": "Note-Taking & Docs", "description": "The leading collaboration software and enterprise wiki for intranets and knowledge management.", "count": 9},
        {"proprietary": "Amazon S3", "open_source": "Minio", "url": "https://min.io", "stars": 50, "category": "Hosting & Infrastructure", "description": "A highly durable, secure, and scalable object storage service from Amazon Web Services.", "count": 6},
        {"proprietary": "Monday.com", "open_source": "Plane", "url": "https://plane.so", "stars": 50, "category": "Project Management", "description": "Streamline workflows, gain clear visibility across teams, and empower smarter decisions with AI.", "count": 25},
        {"proprietary": "TypingMind", "open_source": "AnythingLLM", "url": "https://anythingllm.com", "stars": 60, "category": "AI Chat Interfaces", "description": "Advanced AI chat interface that provides a better user experience with chat folders, search, and custom prompts.", "count": 10},
    ],
    "tools": [
        {"name": "n8n", "description": "Workflow automation with 400+ integrations", "url": "https://n8n.io", "category": "Workflow Automation", "stars": 52, "license": "Sustainable Use License", "github": "n8n-io/n8n"},
        {"name": "AppFlowy", "description": "Open source Notion alternative", "url": "https://appflowy.io", "category": "Note-Taking & Docs", "stars": 58, "license": "AGPL-3.0", "github": "AppFlowy-IO/AppFlowy"},
        {"name": "Supabase", "description": "Open source Firebase alternative", "url": "https://supabase.com", "category": "Backend-as-a-Service", "stars": 76, "license": "Apache-2.0", "github": "supabase/supabase"},
        {"name": "Cal.com", "description": "Open source Calendly alternative", "url": "https://cal.com", "category": "Productivity", "stars": 33, "license": "AGPL-3.0", "github": "calcom/cal.com"},
        {"name": "Plausible", "description": "Simple, privacy-friendly analytics", "url": "https://plausible.io", "category": "Analytics", "stars": 22, "license": "AGPL-3.0", "github": "plausible/analytics"},
        {"name": "PostHog", "description": "Product analytics platform", "url": "https://posthog.com", "category": "Analytics", "stars": 24, "license": "MIT", "github": "PostHog/posthog"},
        {"name": "Metabase", "description": "Business intelligence and analytics", "url": "https://metabase.com", "category": "Analytics", "stars": 40, "license": "AGPL-3.0", "github": "metabase/metabase"},
        {"name": "Mattermost", "description": "Open source Slack alternative", "url": "https://mattermost.com", "category": "Communication", "stars": 30, "license": "AGPL-3.0", "github": "mattermost/mattermost"},
        {"name": "Rocket.Chat", "description": "Open source team messaging", "url": "https://rocket.chat", "category": "Communication", "stars": 41, "license": "MIT", "github": "RocketChat/Rocket.Chat"},
        {"name": "Element", "description": "Matrix-based encrypted messaging", "url": "https://element.io", "category": "Communication", "stars": 35, "license": "Apache-2.0", "github": "element-hq/element-web"},
        {"name": "Outline", "description": "Open source Notion alternative for teams", "url": "https://outline.com", "category": "Note-Taking & Docs", "stars": 29, "license": "BSL-1.1", "github": "outline/outline"},
        {"name": "Strapi", "description": "Open source headless CMS", "url": "https://strapi.io", "category": "CMS & Content", "stars": 65, "license": "MIT", "github": "strapi/strapi"},
        {"name": "Ghost", "description": "Professional publishing platform", "url": "https://ghost.org", "category": "CMS & Content", "stars": 48, "license": "MIT", "github": "TryGhost/Ghost"},
        {"name": "Directus", "description": "Open data platform for headless CMS", "url": "https://directus.io", "category": "CMS & Content", "stars": 29, "license": "MIT", "github": "directus/directus"},
        {"name": "WordPress", "description": "Open source CMS powering 43% of web", "url": "https://wordpress.org", "category": "CMS & Content", "stars": 20, "license": "GPL-2.0", "github": "WordPress/WordPress"},
        {"name": "PocketBase", "description": "Open source backend in one file", "url": "https://pocketbase.io", "category": "Backend-as-a-Service", "stars": 42, "license": "MIT", "github": "pocketbase/pocketbase"},
        {"name": "Appwrite", "description": "Open source Firebase alternative", "url": "https://appwrite.io", "category": "Backend-as-a-Service", "stars": 46, "license": "BSD-3-Clause", "github": "appwrite/appwrite"},
        {"name": "NocoDB", "description": "Open source Airtable alternative", "url": "https://nocodb.com", "category": "Databases", "stars": 51, "license": "GPL-3.0", "github": "nocodb/nocodb"},
        {"name": "Nextcloud", "description": "Open source cloud storage", "url": "https://nextcloud.com", "category": "Hosting & Infrastructure", "stars": 28, "license": "AGPL-3.0", "github": "nextcloud/server"},
        {"name": "GitLab", "description": "Open source DevOps platform", "url": "https://gitlab.com", "category": "CI/CD & Deployment", "stars": 25, "license": "MIT", "github": "gitlabhq/gitlabhq"},
        {"name": "Drone CI", "description": "Continuous delivery platform", "url": "https://drone.io", "category": "CI/CD & Deployment", "stars": 33, "license": "Apache-2.0", "github": "harness/drone"},
        {"name": "Gitea", "description": "Self-hosted Git service", "url": "https://gitea.io", "category": "Developer Tools", "stars": 47, "license": "MIT", "github": "go-gitea/gitea"},
        {"name": "VS Codium", "description": "Free VS Code distribution", "url": "https://vscodium.com", "category": "Developer Tools", "stars": 26, "license": "MIT", "github": "VSCodium/vscodium"},
        {"name": "Ollama", "description": "Run LLMs locally", "url": "https://ollama.ai", "category": "AI & Machine Learning", "stars": 130, "license": "MIT", "github": "ollama/ollama"},
        {"name": "MLflow", "description": "ML lifecycle platform", "url": "https://mlflow.org", "category": "AI & Machine Learning", "stars": 20, "license": "Apache-2.0", "github": "mlflow/mlflow"},
        {"name": "Hugging Face", "description": "AI model hub and libraries", "url": "https://huggingface.co", "category": "AI & Machine Learning", "stars": 140, "license": "Apache-2.0", "github": "huggingface/transformers"},
        {"name": "LangChain", "description": "Build AI-powered applications", "url": "https://langchain.com", "category": "AI & Machine Learning", "stars": 100, "license": "MIT", "github": "langchain-ai/langchain"},
        {"name": "Grafana", "description": "Observability and monitoring", "url": "https://grafana.com", "category": "Monitoring & Observability", "stars": 66, "license": "AGPL-3.0", "github": "grafana/grafana"},
        {"name": "Prometheus", "description": "Monitoring and alerting toolkit", "url": "https://prometheus.io", "category": "Monitoring & Observability", "stars": 57, "license": "Apache-2.0", "github": "prometheus/prometheus"},
        {"name": "Sentry", "description": "Application performance monitoring", "url": "https://sentry.io", "category": "Monitoring & Observability", "stars": 41, "license": "MIT", "github": "getsentry/sentry"},
        {"name": "OpenTelemetry", "description": "Observability framework", "url": "https://opentelemetry.io", "category": "Monitoring & Observability", "stars": 55, "license": "Apache-2.0", "github": "open-telemetry/opentelemetry-collector"},
        {"name": "Docker", "description": "Container platform", "url": "https://docker.com", "category": "Hosting & Infrastructure", "stars": 70, "license": "Apache-2.0", "github": "moby/moby"},
        {"name": "Kubernetes", "description": "Container orchestration", "url": "https://kubernetes.io", "category": "Hosting & Infrastructure", "stars": 112, "license": "Apache-2.0", "github": "kubernetes/kubernetes"},
        {"name": "Terraform", "description": "Infrastructure as code", "url": "https://terraform.io", "category": "Hosting & Infrastructure", "stars": 44, "license": "MPL-2.0", "github": "hashicorp/terraform"},
        {"name": "Minio", "description": "S3-compatible object storage", "url": "https://min.io", "category": "Hosting & Infrastructure", "stars": 50, "license": "AGPL-3.0", "github": "minio/minio"},
        {"name": "Keycloak", "description": "Identity and access management", "url": "https://keycloak.org", "category": "Security & Privacy", "stars": 24, "license": "Apache-2.0", "github": "keycloak/keycloak"},
        {"name": "Bitwarden", "description": "Open source password manager", "url": "https://bitwarden.com", "category": "Password Managers", "stars": 38, "license": "AGPL-3.0", "github": "bitwarden/server"},
        {"name": "Penpot", "description": "Open source Figma alternative", "url": "https://penpot.app", "category": "Design & Creative", "stars": 35, "license": "MPL-2.0", "github": "penpot/penpot"},
        {"name": "Inkscape", "description": "Vector graphics editor", "url": "https://inkscape.org", "category": "Design & Creative", "stars": 22, "license": "GPL-3.0", "github": "inkscape/inkscape"},
        {"name": "GIMP", "description": "Image manipulation program", "url": "https://gimp.org", "category": "Design & Creative", "stars": 18, "license": "GPL-3.0", "github": "GNOME/gimp"},
        {"name": "Blender", "description": "3D creation suite", "url": "https://blender.org", "category": "Design & Creative", "stars": 25, "license": "GPL-3.0", "github": "blender/blender"},
        {"name": "Listmonk", "description": "Self-hosted newsletter manager", "url": "https://listmonk.app", "category": "Marketing & Email", "stars": 15, "license": "AGPL-3.0", "github": "knadh/listmonk"},
        {"name": "Mautic", "description": "Marketing automation platform", "url": "https://mautic.org", "category": "Marketing & Email", "stars": 8, "license": "GPL-3.0", "github": "mautic/mautic"},
        {"name": "Twenty CRM", "description": "Open source CRM", "url": "https://twenty.com", "category": "CRM & Sales", "stars": 24, "license": "AGPL-3.0", "github": "twentyhq/twenty"},
        {"name": "ERPNext", "description": "Open source ERP system", "url": "https://erpnext.com", "category": "ERP & Finance", "stars": 22, "license": "GPL-3.0", "github": "frappe/erpnext"},
        {"name": "Odoo", "description": "Open source ERP and CRM", "url": "https://odoo.com", "category": "ERP & Finance", "stars": 40, "license": "LGPL-3.0", "github": "odoo/odoo"},
        {"name": "Stripe (alternative)", "description": "Payment processing (use Paddle/LemonSqueezy)", "url": "https://lemon.me", "category": "Payment & Billing", "stars": 9, "license": "MIT", "github": "lmsqueezy/lmsqueezy"},
        {"name": "Lemon Squeezy", "description": "Open source payment platform", "url": "https://lemonsqueezy.com", "category": "Payment & Billing", "stars": 7, "license": "MIT", "github": "lmsqueezy/lmsqueezy"},
        {"name": "Stripe", "description": "Payment infrastructure", "url": "https://stripe.com", "category": "Payment & Billing", "stars": 0, "license": "Proprietary", "github": None},
        {"name": "Vite", "description": "Frontend build tool", "url": "https://vitejs.dev", "category": "Developer Tools", "stars": 70, "license": "MIT", "github": "vitejs/vite"},
        {"name": "Prisma", "description": "Next-gen ORM", "url": "https://prisma.io", "category": "Databases", "stars": 42, "license": "Apache-2.0", "github": "prisma/prisma"},
        {"name": "Drizzle ORM", "description": "TypeScript ORM", "url": "https://orm.drizzle.team", "category": "Databases", "stars": 28, "license": "Apache-2.0", "github": "drizzle-team/drizzle-orm"},
        {"name": "PostgreSQL", "description": "Advanced relational database", "url": "https://postgresql.org", "category": "Databases", "stars": 16, "license": "PostgreSQL", "github": "postgres/postgres"},
        {"name": "ClickHouse", "description": "Column-oriented DBMS", "url": "https://clickhouse.com", "category": "Databases", "stars": 38, "license": "Apache-2.0", "github": "ClickHouse/ClickHouse"},
        {"name": "Redis", "description": "In-memory data store", "url": "https://redis.io", "category": "Databases", "stars": 68, "license": "BSL-1.1", "github": "redis/redis"},
        {"name": "Jitsi Meet", "description": "Open source Zoom alternative", "url": "https://jitsi.org", "category": "Video & Conferencing", "stars": 25, "license": "Apache-2.0", "github": "jitsi/jitsi-meet"},
        {"name": "BigBlueButton", "description": "Open source web conferencing", "url": "https://bigbluebutton.org", "category": "Video & Conferencing", "stars": 9, "license": "LGPL-3.0", "github": "bigbluebutton/bigbluebutton"},
        {"name": "OpenProject", "description": "Open source project management", "url": "https://openproject.org", "category": "Project Management", "stars": 10, "license": "GPL-3.0", "github": "opf/openproject"},
        {"name": "Plane", "description": "Open source Jira alternative", "url": "https://plane.so", "category": "Project Management", "stars": 32, "license": "Apache-2.0", "github": "makeplane/plane"},
        {"name": "Taiga", "description": "Agile project management", "url": "https://taiga.io", "category": "Project Management", "stars": 7, "license": "MPL-2.0", "github": "taigaio/taiga-back"},
        {"name": "Focalboard", "description": "Open source Asana alternative", "url": "https://focalboard.com", "category": "Project Management", "stars": 23, "license": "MIT", "github": "mattermost/focalboard"},
        {"name": "Docmost", "description": "Collaborative wiki and docs", "url": "https://docmost.com", "category": "Note-Taking & Docs", "stars": 5, "license": "AGPL-3.0", "github": "docmost/docmost"},
        {"name": "Affine", "description": "Open source Notion alternative", "url": "https://affine.pro", "category": "Note-Taking & Docs", "stars": 45, "license": "MIT", "github": "toeverything/AFFiNE"},
        {"name": "Logseq", "description": "Open source knowledge management", "url": "https://logseq.com", "category": "Note-Taking & Docs", "stars": 35, "license": "AGPL-3.0", "github": "logseq/logseq"},
        {"name": "Joplin", "description": "Open source note-taking app", "url": "https://joplinapp.org", "category": "Note-Taking & Docs", "stars": 48, "license": "AGPL-3.0", "github": "laurent22/joplin"},
        {"name": "Matomo", "description": "Google Analytics alternative", "url": "https://matomo.org", "category": "Analytics", "stars": 21, "license": "GPL-3.0", "github": "matomo-org/matomo"},
        {"name": "Umami", "description": "Simple analytics platform", "url": "https://umami.is", "category": "Analytics", "stars": 22, "license": "MIT", "github": "umami-software/umami"},
        {"name": "NocoDB", "description": "Open source Airtable alternative", "url": "https://nocodb.com", "category": "Forms & Surveys", "stars": 51, "license": "GPL-3.0", "github": "nocodb/nocodb"},
        {"name": "Formbricks", "description": "Open source survey platform", "url": "https://formbricks.com", "category": "Forms & Surveys", "stars": 8, "license": "AGPL-3.0", "github": "formbricks/formbricks"},
        {"name": "Typebot", "description": "Open source chatbots", "url": "https://typebot.io", "category": "Forms & Surveys", "stars": 16, "license": "AGPL-3.0", "github": "baptistearno/typebot.io"},
        {"name": "Documenso", "description": "Open source DocuSign alternative", "url": "https://documenso.com", "category": "Productivity", "stars": 8, "license": "AGPL-3.0", "github": "documenso/documenso"},
        {"name": "OpenSign", "description": "Open source e-signature", "url": "https://opensignlabs.com", "category": "Productivity", "stars": 4, "license": "AGPL-3.0", "github": "opensignlabs/opensign"},
    ],
    "advertise": {
        "pageviews": "450K",
        "listed_projects": "750",
        "newsletter": "10K",
        "github_stars": "5.8K",
        "audience": {
            "developers": 45,
            "tech_leaders": 30,
            "founders_ctos": 20,
            "other": 5
        },
        "plans": [
            {
                "name": "Silver",
                "price": 49,
                "period": "week",
                "features": ["Standard ad placements", "Click & impression tracking", "1x impression weight"]
            },
            {
                "name": "Gold",
                "price": 99,
                "period": "week",
                "features": ["Everything in Silver", "Additional ad placements", "Sponsor logo on homepage", "2.5x impression weight"],
                "popular": True
            },
            {
                "name": "Platinum",
                "price": 199,
                "period": "week",
                "features": ["Everything in Gold", "Exclusive ad placements", "Priority support", "5x impression weight"]
            }
        ],
        "testimonial": {
            "quote": "NovaPulse AI has been a solid traffic source for our website since we partnered up with them. Their homepage spot, in particular, delivered great results, giving us a noticeable 10–20% traffic boost.",
            "author": "Naga Siva",
            "role": "Founder of Notesnook"
        },
        "partner_logos": [
            "InfluxData", "Plasmic", "Databuddy", "Juspay Hyperswitch", "CrawlChat",
            "YNS", "Supalytics", "Vemetric", "CodeRabbit", "Knock", "Railway", "Hetzner",
            "c15t", "Openlane", "Unihost", "Stellar Hosted", "ParityDeals", "Sent",
            "Wispr Flow", "Sevalla", "Prismical", "Logto", "Maileroo", "Efficient App",
            "Seline", "Pulsetic", "Discourse", "Novu", "Polar", "n8n", "Comp AI",
            "ScreenshotOne"
        ]
    },
    "self_hosted_tools": [
        {"name": "Novu", "description": "Multi-channel notification infrastructure for apps", "url": "https://novu.co", "category": "Push Notification Services", "stars": 39009, "forks": 4294, "last_commit": "2 days ago", "license": "MIT", "github": "novuhq/novu", "domain": "novu.co", "alternatives": ["Customer.io"]},
        {"name": "Postiz", "description": "Schedule and manage social media across 30+ networks", "url": "https://postiz.com", "category": "Social Media Management", "stars": 30609, "forks": 5616, "last_commit": "1 day ago", "license": "AGPL-3.0", "github": "gitroomhq/postiz-app", "domain": "postiz.com", "alternatives": ["HootSuite"]},
        {"name": "Cap", "description": "Open source screen recorder with editing and instant sharing", "url": "https://cap.so", "category": "Screen Recording", "stars": 19128, "forks": 1557, "last_commit": "2 days ago", "license": "MIT", "github": "CapSoftware/Cap", "domain": "cap.so", "alternatives": ["Loom"]},
        {"name": "Hanko", "description": "Passkeys, SSO, and 2FA without vendor lock-in", "url": "https://hanko.io", "category": "Authentication & SSO", "stars": 8930, "forks": 1012, "last_commit": "1 day ago", "license": "AGPL-3.0", "github": "teamhanko/hanko", "domain": "hanko.io", "alternatives": ["Clerk"]},
        {"name": "OpenPanel", "description": "Cookie-free web and product analytics, self-hostable", "url": "https://openpanel.dev", "category": "Web Analytics", "stars": 5797, "forks": 366, "last_commit": "2 days ago", "license": "MIT", "github": "openpanel-dev/openpanel", "domain": "openpanel.dev", "alternatives": ["Google Analytics"]},
        {"name": "Baserow", "description": "No-code database and app builder you can self-host", "url": "https://baserow.io", "category": "Low-Code/No-Code", "stars": 4880, "forks": 607, "last_commit": "1 day ago", "license": "MIT", "github": "baserow/baserow", "domain": "baserow.io", "alternatives": ["Airtable"]},
        {"name": "Tolgee", "description": "Open-source localization platform for multilingual apps", "url": "https://tolgee.io", "category": "Translation Management", "stars": 3932, "forks": 357, "last_commit": "1 day ago", "license": "Apache-2.0", "github": "tolgee/tolgee-platform", "domain": "tolgee.io", "alternatives": ["Crowdin"]},
        {"name": "LearnHouse", "description": "Build, share & monetize courses with modern open-source LMS", "url": "https://learnhouse.app", "category": "Learning Management Systems", "stars": 1643, "forks": 327, "last_commit": "1 day ago", "license": "AGPL-3.0", "github": "learnhouse/learnhouse", "domain": "learnhouse.app", "alternatives": ["Miro"]},
        {"name": "OpenClaw", "description": "Personal AI assistant that acts through your chat apps", "url": "https://openclaw.ai", "category": "AI Personal Assistants", "stars": 374038, "forks": 77740, "last_commit": "1 day ago", "license": "Apache-2.0", "github": "openclaw/openclaw", "domain": "openclaw.ai", "alternatives": ["Zo Computer"]},
        {"name": "n8n", "description": "Visual workflow automation with code flexibility and AI agents", "url": "https://n8n.io", "category": "Workflow Automation", "stars": 189341, "forks": 57921, "last_commit": "1 day ago", "license": "Sustainable Use License", "github": "n8n-io/n8n", "domain": "n8n.io", "alternatives": ["Make"]},
        {"name": "Open WebUI", "description": "Self-hosted AI interface for any model, any team", "url": "https://openwebui.com", "category": "AI Chat Interfaces", "stars": 138289, "forks": 19774, "last_commit": "2 days ago", "license": "MIT", "github": "open-webui/open-webui", "domain": "openwebui.com", "alternatives": ["Claude"]},
        {"name": "Dify", "description": "Build and deploy autonomous AI agents without coding", "url": "https://dify.ai", "category": "AI Agent Platforms", "stars": 142298, "forks": 22382, "last_commit": "1 day ago", "license": "Apache-2.0", "github": "langgenius/dify", "domain": "dify.ai", "alternatives": ["Retool"]},
        {"name": "Langflow", "description": "Visual builder for AI-powered applications and workflows", "url": "https://langflow.org", "category": "AI Development Platforms", "stars": 148678, "forks": 9096, "last_commit": "1 day ago", "license": "MIT", "github": "langflow-ai/langflow", "domain": "langflow.org", "alternatives": ["Voiceflow"]},
        {"name": "Firecrawl", "description": "Blazing-fast web crawling for modern developers", "url": "https://firecrawl.dev", "category": "Web Crawlers", "stars": 123144, "forks": 7468, "last_commit": "1 day ago", "license": "AGPL-3.0", "github": "nicksherron/firecrawl", "domain": "firecrawl.dev", "alternatives": ["Browserbase"]},
        {"name": "RustDesk", "description": "Secure, fast, and open-source remote desktop software", "url": "https://rustdesk.com", "category": "Remote Desktop", "stars": 114779, "forks": 17303, "last_commit": "2 days ago", "license": "AGPL-3.0", "github": "rustdesk/rustdesk", "domain": "rustdesk.com", "alternatives": ["AnyDesk"]},
        {"name": "Supabase", "description": "Open-source Firebase alternative for modern app development", "url": "https://supabase.com", "category": "Backend-as-a-Service", "stars": 102889, "forks": 12516, "last_commit": "1 day ago", "license": "Apache-2.0", "github": "supabase/supabase", "domain": "supabase.com", "alternatives": ["Firebase"]},
        {"name": "Immich", "description": "Self-hosted photo and video backup solution", "url": "https://immich.app", "category": "Photo & Video Management", "stars": 101349, "forks": 5666, "last_commit": "1 day ago", "license": "AGPL-3.0", "github": "immich-app/immich", "domain": "immich.app", "alternatives": ["Google Photos"]},
        {"name": "Uptime Kuma", "description": "Self-hosted monitoring tool for websites and services", "url": "https://uptime.kuma.pet", "category": "Uptime Monitoring", "stars": 87109, "forks": 7882, "last_commit": "1 day ago", "license": "MIT", "github": "louislam/uptime-kuma", "domain": "uptime.kuma.pet", "alternatives": ["Opsgenie"]},
        {"name": "OpenHands", "description": "Open-source platform for scalable cloud coding agents", "url": "https://openhands.ai", "category": "AI Coding Agents", "stars": 74555, "forks": 9444, "last_commit": "1 day ago", "license": "MIT", "github": "All-Hands-AI/OpenHands", "domain": "openhands.ai", "alternatives": ["Claude Code"]},
        {"name": "Flowise AI", "description": "Visual builder for AI agents and LLM workflows", "url": "https://flowiseai.com", "category": "AI Integration Platforms", "stars": 53011, "forks": 24378, "last_commit": "3 days ago", "license": "Apache-2.0", "github": "FlowiseAI/Flowise", "domain": "flowiseai.com", "alternatives": ["n8n"]},
        {"name": "Apache Superset", "description": "Modern data exploration and visualization platform", "url": "https://superset.apache.org", "category": "BI Platforms", "stars": 72957, "forks": 17359, "last_commit": "1 day ago", "license": "Apache-2.0", "github": "apache/superset", "domain": "superset.apache.org", "alternatives": ["Power BI"]},
        {"name": "Affine", "description": "Docs, whiteboards, and databases in one workspace", "url": "https://affine.pro", "category": "Collaborative Workspaces", "stars": 68641, "forks": 4875, "last_commit": "1 day ago", "license": "MIT", "github": "toeverything/AFFiNE", "domain": "affine.pro", "alternatives": ["Notion"]},
        {"name": "AppFlowy", "description": "AI workspace for docs, projects, and wikis you control", "url": "https://appflowy.io", "category": "Collaborative Workspaces", "stars": 71105, "forks": 5304, "last_commit": "12 days ago", "license": "AGPL-3.0", "github": "AppFlowy-IO/AppFlowy", "domain": "appflowy.io", "alternatives": ["Notion"]},
        {"name": "AnythingLLM", "description": "Chat with your documents using any LLM, fully private", "url": "https://anythingllm.com", "category": "AI Chat Interfaces", "stars": 60486, "forks": 6545, "last_commit": "1 day ago", "license": "MIT", "github": "Mintplex-Labs/anything-llm", "domain": "anythingllm.com", "alternatives": ["Claude"]},
        {"name": "Grafana", "description": "Open source analytics and monitoring solution", "url": "https://grafana.com", "category": "Infrastructure Monitoring", "stars": 73942, "forks": 13943, "last_commit": "1 day ago", "license": "AGPL-3.0", "github": "grafana/grafana", "domain": "grafana.com", "alternatives": ["Power BI"]},
        {"name": "Strapi", "description": "Craft and manage content with ease and flexibility", "url": "https://strapi.io", "category": "Headless CMS", "stars": 72228, "forks": 9730, "last_commit": "2 days ago", "license": "MIT", "github": "strapi/strapi", "domain": "strapi.io", "alternatives": ["Sanity"]},
        {"name": "Odoo", "description": "All-in-one business management suite for modern enterprises", "url": "https://odoo.com", "category": "ERP Systems", "stars": 51215, "forks": 32518, "last_commit": "1 day ago", "license": "LGPL-3.0", "github": "odoo/odoo", "domain": "odoo.com", "alternatives": ["HubSpot"]},
        {"name": "Maybe", "description": "Empower your financial future with AI-driven insights", "url": "https://maybe.co", "category": "Finance & Fintech", "stars": 54134, "forks": 5606, "last_commit": "10 months ago", "license": "AGPL-3.0", "github": "maybe-finance/maybe", "domain": "maybe.co", "alternatives": ["YNAB"]},
        {"name": "PocketBase", "description": "Open-source backend in a single file", "url": "https://pocketbase.io", "category": "Backend-as-a-Service", "stars": 58500, "forks": 3389, "last_commit": "2 days ago", "license": "MIT", "github": "pocketbase/pocketbase", "domain": "pocketbase.io", "alternatives": ["Supabase"]},
        {"name": "Memos", "description": "Self-hosted timeline for quick notes, logs, and snippets", "url": "https://memos.com", "category": "Note-Taking", "stars": 59977, "forks": 4400, "last_commit": "8 days ago", "license": "MIT", "github": "usememos/memos", "domain": "memos.com", "alternatives": ["Notion"]},
        {"name": "NocoDB", "description": "Transform databases into intuitive spreadsheets instantly", "url": "https://nocodb.com", "category": "Low-Code/No-Code", "stars": 63097, "forks": 4786, "last_commit": "1 day ago", "license": "GPL-3.0", "github": "nocodb/nocodb", "domain": "nocodb.com", "alternatives": ["Airtable"]},
        {"name": "Coolify", "description": "Self-hosted cloud platform for effortless deployment", "url": "https://coolify.io", "category": "PaaS & Deployment", "stars": 55769, "forks": 4623, "last_commit": "2 days ago", "license": "Apache-2.0", "github": "coollabsio/coolify", "domain": "coolify.io", "alternatives": ["Vercel"]},
        {"name": "Plane", "description": "Project management for teams and AI agents", "url": "https://plane.so", "category": "Project Management", "stars": 49582, "forks": 4325, "last_commit": "3 days ago", "license": "Apache-2.0", "github": "makeplane/plane", "domain": "plane.so", "alternatives": ["Linear"]},
        {"name": "Appwrite", "description": "Open-source backend platform for rapid app development", "url": "https://appwrite.io", "category": "Backend-as-a-Service", "stars": 56125, "forks": 5378, "last_commit": "1 day ago", "license": "BSD-3-Clause", "github": "appwrite/appwrite", "domain": "appwrite.io", "alternatives": ["Supabase"]},
        {"name": "Cal.com", "description": "Customizable scheduling that works the way you do", "url": "https://cal.com", "category": "Appointment Scheduling", "stars": 44369, "forks": 13635, "last_commit": "9 days ago", "license": "AGPL-3.0", "github": "calcom/cal.com", "domain": "cal.com", "alternatives": ["Calendly"]},
        {"name": "Twenty", "description": "Streamline customer relationships with modern CRM", "url": "https://twenty.com", "category": "CRM Systems", "stars": 46042, "forks": 6493, "last_commit": "1 day ago", "license": "AGPL-3.0", "github": "twentyhq/twenty", "domain": "twenty.com", "alternatives": ["HubSpot"]},
        {"name": "Gitea", "description": "Self-hosted Git service for seamless collaboration", "url": "https://gitea.com", "category": "Git Platforms", "stars": 55860, "forks": 6715, "last_commit": "1 day ago", "license": "MIT", "github": "go-gitea/gitea", "domain": "gitea.com", "alternatives": ["GitHub"]},
        {"name": "Ghost", "description": "Modern publishing platform for creators and businesses", "url": "https://ghost.org", "category": "Blogging Platforms", "stars": 53638, "forks": 11654, "last_commit": "1 day ago", "license": "MIT", "github": "TryGhost/Ghost", "domain": "ghost.org", "alternatives": ["WordPress"]},
        {"name": "Meilisearch", "description": "Lightning-fast search for your applications", "url": "https://meilisearch.com", "category": "Search Engines", "stars": 57688, "forks": 2550, "last_commit": "3 days ago", "license": "MIT", "github": "meilisearch/meilisearch", "domain": "meilisearch.com", "alternatives": ["Algolia"]},
        {"name": "Joplin", "description": "Your secure, open-source note-taking companion", "url": "https://joplinapp.org", "category": "Note-Taking", "stars": 54913, "forks": 6106, "last_commit": "1 day ago", "license": "AGPL-3.0", "github": "laurent22/joplin", "domain": "joplinapp.org", "alternatives": ["Obsidian"]},
        {"name": "Jellyfin", "description": "Self-hosted media server for movies, music, and more", "url": "https://jellyfin.org", "category": "Media Servers", "stars": 51909, "forks": 4831, "last_commit": "2 days ago", "license": "GPL-2.0", "github": "jellyfin/jellyfin", "domain": "jellyfin.org", "alternatives": ["Netflix"]},
        {"name": "Jan", "description": "Your AI-powered local assistant for seamless productivity", "url": "https://jan.ai", "category": "AI Chat Interfaces", "stars": 42631, "forks": 2876, "last_commit": "1 day ago", "license": "AGPL-3.0", "github": "janhq/jan", "domain": "jan.ai", "alternatives": ["Claude"]},
    ],
    "licenses": [
        {"name": "AGPL-3.0", "count": 165},
        {"name": "Apache-2.0", "count": 187},
        {"name": "GPL-3.0", "count": 139},
        {"name": "MPL-2.0", "count": 45},
        {"name": "BSD-3-Clause", "count": 15},
        {"name": "GPL-2.0", "count": 10},
        {"name": "BSD-2-Clause", "count": 10},
        {"name": "LGPL-2.1", "count": 2},
        {"name": "EPL-2.0", "count": 4},
        {"name": "ISC", "count": 1}
    ],
    "navigation": [
        {"name": "Browse", "href": "/browse", "icon": "🔍"},
        {"name": "Categories", "href": "/categories", "icon": "📂"},
        {"name": "Tech Stacks", "href": "/tech-stacks", "icon": "⚙️"},
        {"name": "Self-hosted", "href": "/self-hosted", "icon": "🏠"},
        {"name": "Tags", "href": "/tags", "icon": "🏷️"},
        {"name": "Licenses", "href": "/licenses", "icon": "📜"},
        {"name": "Discount Codes", "href": "/discount-codes", "icon": "🏷️"},
        {"name": "Advertise", "href": "/advertise", "icon": "📢"},
    ],
    "tags": [
        {"name": "AI", "count": 156}, {"name": "Self Hosted", "count": 142}, {"name": "SaaS", "count": 98},
        {"name": "Developer Tools", "count": 87}, {"name": "API", "count": 76}, {"name": "Open Source", "count": 72},
        {"name": "CLI", "count": 65}, {"name": "Automation", "count": 58}, {"name": "Analytics", "count": 52},
        {"name": "Database", "count": 48}, {"name": "CMS", "count": 45}, {"name": "Monitoring", "count": 42},
        {"name": "Security", "count": 40}, {"name": "Machine Learning", "count": 38}, {"name": "DevOps", "count": 36},
        {"name": "Privacy", "count": 34}, {"name": "Collaboration", "count": 32}, {"name": "CRM", "count": 30},
        {"name": "No-Code", "count": 28}, {"name": "Low-Code", "count": 26}, {"name": "ERP", "count": 24},
        {"name": "Authentication", "count": 22}, {"name": "Communication", "count": 20}, {"name": "Productivity", "count": 18},
        {"name": "Email", "count": 16}, {"name": "RAG", "count": 15}, {"name": "Agent", "count": 14},
        {"name": "Vector Database", "count": 13}, {"name": "Web Scraping", "count": 12}, {"name": "Workflow", "count": 11},
    ],
    "discount_codes": [
        {"name": "Plausible", "code": "OPENSOURCE20", "discount": "20% off", "url": "https://plausible.io", "expires": "2026-12-31", "category": "Analytics"},
        {"name": "PostHog", "code": "OSS30", "discount": "30% off first year", "url": "https://posthog.com", "expires": "2026-12-31", "category": "Analytics"},
        {"name": "Sentry", "code": "TEAM10", "discount": "10% off Team plan", "url": "https://sentry.io", "expires": "2026-12-31", "category": "Monitoring"},
        {"name": "Cal.com", "code": "SELFHOST", "discount": "25% off", "url": "https://cal.com", "expires": "2026-12-31", "category": "Productivity"},
        {"name": "NocoDB", "code": "OPENSOURCE", "discount": "15% off", "url": "https://nocodb.com", "expires": "2026-12-31", "category": "Databases"},
        {"name": "Supabase", "code": "LAUNCH50", "discount": "50% off Pro", "url": "https://supabase.com", "expires": "2026-09-30", "category": "Backend"},
        {"name": "Metabase", "code": "STARTUP20", "discount": "20% off", "url": "https://metabase.com", "expires": "2026-12-31", "category": "Analytics"},
        {"name": "Ghost", "code": "CREATOR25", "discount": "25% off", "url": "https://ghost.org", "expires": "2026-12-31", "category": "Publishing"},
        {"name": "Strapi", "code": "DEV30", "discount": "30% off", "url": "https://strapi.io", "expires": "2026-12-31", "category": "CMS"},
        {"name": "Listmonk", "code": "EARLY50", "discount": "50% off", "url": "https://listmonk.app", "expires": "2026-06-30", "category": "Email"},
    ],
    "blog_posts": [
        {"title": "Why Open Source is the Future of Software", "slug": "open-source-future", "date": "2026-05-20", "author": "NovaPulse AI Team", "excerpt": "The shift from proprietary to open source software is accelerating. Here's why.", "category": "Industry Insights", "read_time": "5 min"},
        {"title": "Top 10 Self-Hosted Tools for 2026", "slug": "top-self-hosted-2026", "date": "2026-05-15", "author": "NovaPulse AI Team", "excerpt": "Our curated list of must-have self-hosted tools that give you full control over your data.", "category": "Guides", "read_time": "8 min"},
        {"title": "How to Migrate from SaaS to Open Source", "slug": "migrate-saas-to-opensource", "date": "2026-05-10", "author": "NovaPulse AI Team", "excerpt": "A step-by-step guide to transitioning your team from paid SaaS tools to open source alternatives.", "category": "Guides", "read_time": "10 min"},
        {"title": "Understanding Open Source Licenses", "slug": "open-source-licenses-guide", "date": "2026-05-05", "author": "NovaPulse AI Team", "excerpt": "A comprehensive guide to choosing the right open source license for your project.", "category": "Education", "read_time": "12 min"},
        {"title": "Building an AI Stack with Open Source Tools", "slug": "open-source-ai-stack", "date": "2026-04-28", "author": "NovaPulse AI Team", "excerpt": "How to build a production-ready AI infrastructure using only open source components.", "category": "Tutorials", "read_time": "15 min"},
    ],
}
